name: wave_custom_clone
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.2
  intl: ^0.17.0
  page_transition: ^2.0.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.2
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: OPTIsupAuvantGothicBold
      fonts:
        - asset: assets/fonts/OPTIsupAuvantGothicBold.otf